"use client";

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-white text-gray-800 px-6 py-20">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-4xl font-bold tracking-tight mb-6">
          Terms of Service
        </h1>

        <p className="text-gray-600 mb-8 text-lg">
          Effective Date: June 22, 2025
        </p>

        <section className="space-y-6 text-base leading-relaxed">
          <p>
            These Terms of Service (“Terms”) govern your access to and use of
            GenZilla’s generative AI tools and platform. By accessing or using
            our services, you agree to be bound by these Terms.
          </p>

          <h2 className="text-xl font-semibold text-gray-800">
            1. Use of the Platform
          </h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>You must be at least 13 years old to use GenZilla.</li>
            <li>
              You may use our tools only for lawful and authorized purposes.
            </li>
            <li>
              You are responsible for all activity under your account and must
              safeguard your credentials.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-gray-800">
            2. Intellectual Property
          </h2>
          <p>
            GenZilla and its logo, UI components, and underlying technology are
            the intellectual property of GenZilla Technologies Pvt. Ltd. You may
            not copy, modify, or distribute our materials without permission.
          </p>

          <h2 className="text-xl font-semibold text-gray-800">
            3. User-Generated Content
          </h2>
          <p>
            Any content you generate using GenZilla tools remains your property,
            but we reserve the right to anonymize and analyze it to improve
            platform functionality.
          </p>

          <h2 className="text-xl font-semibold text-gray-800">
            4. Limitations & Disclaimers
          </h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              We do not guarantee that the content generated by GenZilla is
              accurate, complete, or legal.
            </li>
            <li>
              GenZilla is provided “as is” without warranties of any kind.
            </li>
            <li>
              We are not liable for any indirect, incidental, or consequential
              damages resulting from your use of the platform.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-gray-800">
            5. Account Suspension or Termination
          </h2>
          <p>
            We reserve the right to suspend or terminate your account if you
            violate these Terms or misuse the platform in any way.
          </p>

          <h2 className="text-xl font-semibold text-gray-800">
            6. Modifications to the Terms
          </h2>
          <p>
            We may update these Terms from time to time. Continued use of the
            platform constitutes your acceptance of the new Terms.
          </p>

          <h2 className="text-xl font-semibold text-gray-800">
            7. Governing Law
          </h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of India, without regard to its conflict of law principles.
          </p>

          <h2 className="text-xl font-semibold text-gray-800">8. Contact Us</h2>
          <p>
            For questions regarding these Terms, please contact us at{" "}
            <a
              href="mailto:legal@genzilla.ai"
              className="text-blue-600 underline"
            >
              legal@genzilla.ai
            </a>
            .
          </p>
        </section>

        <div className="mt-10 text-sm text-gray-500">
          &copy; {new Date().getFullYear()} GenZilla Technologies Pvt. Ltd. All
          rights reserved.
        </div>
      </div>
    </main>
  );
}
